### ISSUE TITLE
プロフィールのタブを切り替えると、Airticleを収集してしまう

### ISSUE THREAD

**Issue by NoritakaIkeda** [Campers0709/Smore#33]
タブを切り替えまくると、アーティクルがどんどんたくさん読み込まれる挙動をする

**Comment by seitamuro** [comment]
すばやく切り替えまくるとAPIからのレスポンスのタイムラグの問題でカテゴリタブでArticleを収集しているように見えているだけで、実際は収集していないっぽいです
個人的にはこのままcloseでいい気がします

**Comment by seitamuro** [comment]
タブが選択されるたびに記事一覧取得APIとカテゴリ一覧取得APIが呼び出されていることで
記事がない状態でもAPIを叩いているようです

タブが呼び出されるたびにAPIを叩くというのをやめたほうがよさそう
